version: "3.8"
services:
  judge_db:
    image: postgres
    container_name: judge_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres