# This file is in no way production-ready - it is just for easier demo startup
# The app is ran in development mode, and passwords are hardcoded

services:
  db:
    image: postgres:16.3
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rabbit_mq:
    image: rabbitmq:3.12-management
    container_name: rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - type: bind
        source: ./rabbit_mq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbit_mq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbit_mq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 3s
      retries: 5
  server:
    build: server
    container_name: server
    restart: always
    ports:
      - 4000:4000
    environment:
      - AMQP_HOST=rabbit_mq
      - POSTGRES_HOST=db
    depends_on:
      - rabbit_mq
      - db
  worker:
    build: worker
    restart: always
    environment:
      - AMQP_HOST=rabbit_mq
    depends_on:
      - rabbit_mq
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
