name: 'build & publish docker image'

inputs:
  directory:
    description: 'Where to execute the build'
    required: true
  image-name:
    description: 'The name of the image'
    required: true
  docker-token:
    description: "The docker token for login"
    required: true

outputs:
  image-version:
    description: 'The version of the image'
    value: ${{steps.version.outputs.IMAGE_VERSON}}
  image-full-name:
    description: "The full image name - including the registry and version"
    value: ${{steps.version.outputs.IMAGE_NAME}}

runs:
  using: "composite"
  steps:
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.docker-token }}

    - name: Calculate image version
      id: version
      shell: bash
      run: |
        export IMAGE_VERSION=$(git rev-list HEAD --count --first-parent)
        echo "IMAGE_VERSION=${IMAGE_VERSION}" >> "$GITHUB_OUTPUT"
        echo "IMAGE_NAME=ghcr.io/yordaniliev2002/${{inputs.image-name}}:${IMAGE_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Build image
      shell: bash
      run: |
        cd ${{inputs.directory}}
        docker build -t ${{steps.version.outputs.IMAGE_NAME}} .

    - name: Publish image
      shell: bash
      run: docker push ${{steps.version.outputs.IMAGE_NAME}}

