apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exposer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: judge-rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30003
