apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: judge-postgres-pv-claim
  labels:
    app: judge-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
