apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-server-deployment
  labels:
    app: judge-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: judge-server
  template:
    metadata:
      labels:
        app: judge-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: judge-server-container
          ports:
            - containerPort: 4000
          # TODO - change the version
          image: ghcr.io/yordaniliev2002/judge-server:35
          env:
            - name: AMQP_HOST
              value: judge-rabbitmq.default.svc
            - name: AMQP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: judge-rabbitmq-default-user
                  key: username
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: judge-rabbitmq-default-user
                  key: password
            - name: POSTGRES_HOST
              value: judge-postgres.default.svc
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
